version: '2'
services:
  database:
    image: "postgres:9.6"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  pgadmin:
      image: "fenglc/pgadmin4"
      links:
        - "database:postgres"
      ports:
        - "5050:5050"
