version: "2"
services:
    database:
        image: "postgres:9.6"
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
        ports:
            - "5432:5432"
        volumes:
            - /tmp/db_backup:/tmp/db_backup
    adminer:
        image: adminer
        links:
            - "database:postgres"
        ports:
            - 8080:8080
